server:
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/tree"
    username: "tree"
    password: "tree"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    dropFirst: false
    changeLog: "classpath:/db/changelog/db.changelog-master.xml"